### ISSUE TITLE
Fix (or remove) tests

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-resource-list-examples#13]
Tests are currently failing: https://circleci.com/gh/Shopify/polaris-resource-list-examples/2

**Comment by ry5n** [comment]
Indeed. This is what I see in the error log:

```
renders without crashing

    TypeError: Cannot read property 'createElement' of undefined
    at Truncate$1 (node_modules/@shopify/polaris/index.js:4523:27)
```

That would be React.createElement, which looks like so in the bundle:

```
function Truncate$1(_ref) {
    var children = _ref.children;

    return React__default.createElement(
        'span',
        { className: styles$36.Truncate },
        children
    );
}
```

Not sure what’s going on here since the app runs fine and there doesn’t seem to be anything wrong with the Truncate component…
